---
title: "matrixpaper"
author: "Felipe"
date: "2024-08-18"
output: html_document
---
Load Matrisome
```{r}
matrisome <- read.csv("/Users/Felipe/Desktop/MATRIX/exomatrix8-18-2024.csv")
matrisome$Category <- matrisome$Matrisome.Category
matrisome$Matrisome.Category <- NULL
matrisome$Category[matrisome$Category == "Collagens"] <- "Collagen"
matrisome$Category[matrisome$Category == "ECM Glycoproteins"] <- "Glycoprotein"
matrisome$Category[matrisome$Category == "Proteoglycans"] <- "Proteoglycan"
matrisome$Category[matrisome$Category == "ECM-affiliated"] <- "ECM-Affiliated"
matrisome$Category[matrisome$Category == "ECM Regulators"] <- "ECM-Regulators"
matrisome$Category[matrisome$Category == "Secreted Factors"] <- "ECM-Secreted"
```

Load Protein Data
```{r}
proteome18gw <- read.csv("/Users/Felipe/Desktop/MATRIX/18gw_2022_human.csv")

#Eliminate layers we do not need
proteome18gw$WC_2_E <- NULL
proteome18gw$GZ_3_E <- NULL
proteome18gw$L1CP_4_E <- NULL
```

Let's filter out proteome GW18 using matrisome
```{r}
proteome18gw <- proteome18gw[proteome18gw$Gene.symbol %in% matrisome$Gene.Symbol, ]
proteome18gw <- merge(proteome18gw, matrisome, by.x = "Gene.symbol", by.y = "Gene.Symbol", all.x = TRUE)


```

Split protein data based on the classification.

```{r}
prot_collagens <- proteome18gw[proteome18gw$Category == "Collagen", ]
prot_glyco <- proteome18gw[proteome18gw$Category == "Glycoprotein", ]
prot_proteogly <- proteome18gw[proteome18gw$Category == "Proteoglycan", ]
prot_ECM_reg <- proteome18gw[proteome18gw$Category == "ECM-Regulators", ]
prot_ECM_aff <- proteome18gw[proteome18gw$Category == "ECM-Affiliated", ]
prot_ECM_sec <- proteome18gw[proteome18gw$Category == "ECM-Secreted", ]
prot_others <- proteome18gw[proteome18gw$Category == "Others", ]
```
Let's start with the Germinal Zone (GZ) comprised by the VZ and SVZ.

```{r}
mrna_vz_svz <- read.csv("/Users/Felipe/Desktop/MATRIX/MidGestation_VZ.SVZ_Only.psuedobulk.sample.columns (1).csv")
mrna_vz_svz$GW17.Donor..1 <- NULL
mrna_vz_svz$GW17.Donor..2 <- NULL
mrna_vz_svz <- mrna_vz_svz[mrna_vz_svz$X %in% proteome18gw$Gene.symbol, ]
#Calculate the Average individually per subset after imputing zeros.
#mrna_vz_svz$Average <- rowMeans(mrna_vz_svz[, c("GW18.Donor..1", "GW18.Donor..2")])
mrna_vz_svz <- merge(mrna_vz_svz, matrisome, by.x = "X", by.y = "Gene.Symbol",all.x = T)
```

COLLAGENS GERMINAL ZONE


```{r}
#I'm going to use both 18 GW samples and impute the zero values in proteins that were not detected
#I'll calculate the geometric mean instead of the mean since it's better for data that has different orders of mangnitude like signal abundance where i have 10 fold differences in some cases.

# Step 1: Identify the minimum non-zero value across the 'prot_collagens' subset
min_value_gz3e <- min(prot_collagens$GZ_3_E[prot_collagens$GZ_3_E > 0], na.rm = TRUE)
min_value_gz3c <- min(prot_collagens$GZ_3_C[prot_collagens$GZ_3_C > 0], na.rm = TRUE)

# Step 2: Choose a small constant, e.g., half of the minimum non-zero value within the subset
small_value <- min(min_value_gz3e, min_value_gz3c) / 2

# Step 3: Replace zeros in 'prot_collagens' with this small constant
prot_collagens$GZ_3_E[prot_collagens$GZ_3_E == 0] <- small_value
prot_collagens$GZ_3_C[prot_collagens$GZ_3_C == 0] <- small_value

# Step 4: Calculate Unified Abundance (e.g., using Geometric Mean)
prot_collagens$Unified_Abundance <- sqrt(prot_collagens$GZ_3_E * prot_collagens$GZ_3_C)

#Step 5: Order Proteins Based on Abundance
s1 <- order(prot_collagens$Unified_Abundance, decreasing = TRUE)

# Use the sorted_indices to rearrange the data frame
prot_collagens <- prot_collagens[s1, ]

#Let's assign a ranking now

prot_collagens$Ranking.p<- rank(-prot_collagens$Unified_Abundance, ties.method = "first" )

```


```{r}
#Delete columns that i'm not going to need 
prot_collagens$WC_2_C <- NULL
prot_collagens$SP_1_C <- NULL
prot_collagens$L1CP_4_C <- NULL
prot_collagens$WC_2_E <- NULL
prot_collagens$L1CP_4_E <- NULL
```


Let's do the mRNA now.
Split data based on the classification.

```{r}
mrna_collagens <- mrna_vz_svz[mrna_vz_svz$Category == "Collagen", ]
mrna_glyco <- mrna_vz_svz[mrna_vz_svz$Category == "Glycoprotein", ]
mrna_proteogly <- mrna_vz_svz[mrna_vz_svz$Category == "Proteoglycan", ]
mrna_ECM_reg <- mrna_vz_svz[mrna_vz_svz$Category == "ECM-Regulators", ]
mrna_ECM_aff <- mrna_vz_svz[mrna_vz_svz$Category == "ECM-Affiliated", ]
mrna_ECM_sec <- mrna_vz_svz[mrna_vz_svz$Category == "ECM-Secreted", ]
mrna_others <- mrna_vz_svz[mrna_vz_svz$Category == "Others", ]
```
Impute zeros
```{r}
# Step 1: Identify the minimum non-zero value across the 'prot_collagens' subset
min_value_donor1 <- min(mrna_collagens$GW18.Donor..1[mrna_collagens$GW18.Donor..1 > 0], na.rm = TRUE)
min_value_donor2 <- min(mrna_collagens$GW18.Donor..2[mrna_collagens$GW18.Donor..2 > 0], na.rm = TRUE)

# Step 2: Choose a small constant, e.g., half of the minimum non-zero value within the subset
small_value <- min(min_value_donor1, min_value_donor2) / 2

# Step 3: Replace zeros in 'prot_collagens' with this small constant
mrna_collagens$GW18.Donor..1[mrna_collagens$GW18.Donor..1 == 0] <- small_value
mrna_collagens$GW18.Donor..2[mrna_collagens$GW18.Donor..2 == 0] <- small_value

# Step 4: Calculate Unified Abundance (e.g., using Geometric Mean)
mrna_collagens$Average <- rowMeans(mrna_collagens[, c("GW18.Donor..1", "GW18.Donor..2")])
```

```{r}
#Let's do the same for the mrna data of the collagens
s2 <- order(mrna_collagens$Average, decreasing = TRUE)
mrna_collagens<- mrna_collagens[s2, ]
mrna_collagens$Ranking.m <- rank(-mrna_collagens$Average, ties.method = "first")
#Merge protein  data with mRNA ranking
prot_collagens <- merge(prot_collagens, mrna_collagens, by.x = 'Gene.symbol', by.y = 'X', all.x = TRUE)

#Let's save the csv and excel file.
#write_xlsx(prot_collagens, "/Users/Felipe/Desktop/MATRIX/mRNAvsProtein 18GW human/Germinal Zone/prot_mrna_collagens_GZ_VZSVS_18GW.xlsx")
#write.csv(prot_collagens, "/Users/Felipe/Desktop/MATRIX/mRNAvsProtein 18GW human/Germinal Zone/prot_mrna_collagens_GZ_VZSVS_18GW.csv",row.names = F)
```

Let's do Glycoproteins now.

```{r}
# Step 1: Identify the minimum non-zero value across the 'prot_collagens' subset
min_value_gz3e <- min(prot_glyco$GZ_3_E[prot_glyco$GZ_3_E > 0], na.rm = TRUE)
min_value_gz3c <- min(prot_glyco$GZ_3_C[prot_glyco$GZ_3_C > 0], na.rm = TRUE)

# Step 2: Choose a small constant, e.g., half of the minimum non-zero value within the subset
small_value <- min(min_value_gz3e, min_value_gz3c) / 2

# Step 3: Replace zeros in 'prot_glyco' with this small constant
prot_glyco$GZ_3_E[prot_glyco$GZ_3_E == 0] <- small_value
prot_glyco$GZ_3_C[prot_glyco$GZ_3_C == 0] <- small_value

# Step 4: Calculate Unified Abundance (e.g., using Geometric Mean)
prot_glyco$Unified_Abundance <- sqrt(prot_glyco$GZ_3_E * prot_glyco$GZ_3_C)

#Step 5: Order Proteins Based on Abundance
s1 <- order(prot_glyco$Unified_Abundance, decreasing = TRUE)

# Use the sorted_indices to rearrange the data frame
prot_glyco <- prot_glyco[s1, ]

#Let's assign a ranking now

prot_glyco$Ranking.p<- rank(-prot_glyco$Unified_Abundance, ties.method = "first" )
```


